from __future__ import annotations

from copy import deepcopy
from typing import Any


PLOT_STUDIO_VERSION = "0.1"
PLOTLY_PALETTE = [
    "#0f8a8f",
    "#315fd6",
    "#c44f3a",
    "#20804f",
    "#7a4fb3",
    "#b7791f",
    "#2d7a9f",
    "#9a3f6f",
]
SUPPORTED_PLOTLY_SPEC_TYPES = {
    "scatter",
    "boxplot",
    "violin",
    "bar",
    "line",
    "histogram",
    "density_contour",
    "scatter_3d",
    "surface_3d",
    "radar",
    "parallel_coordinates",
    "waterfall",
    "ma_plot",
    "qq_plot",
    "forest_plot",
    "roc_curve",
    "pr_curve",
    "kaplan_meier",
    "bland_altman",
    "dose_response",
    "paired_dot",
    "bubble",
    "volcano",
    "upset",
    "venn",
    "heatmap",
    "correlation",
    "enrichment_dot",
}

ADVANCED_PARAMETER_GROUP_IDS = {"theme", "labels", "export", "style", "reference", "guides", "interaction"}

PLOT_WORKFLOW_STAGES = [
    {
        "id": "source",
        "label": "Select source",
        "description": "Attach an upstream analysis output or uploaded table before choosing a chart.",
    },
    {
        "id": "plot",
        "label": "Choose plot",
        "description": "Pick a recommended figure type or browse the full plotting toolbox.",
    },
    {
        "id": "mapping",
        "label": "Map data",
        "description": "Bind numeric, categorical, label, size, and color columns to figure roles.",
    },
    {
        "id": "parameters",
        "label": "Tune parameters",
        "description": "Adjust basic display controls first, then expand advanced styling and export options.",
    },
    {
        "id": "preview",
        "label": "Render preview",
        "description": "Run the interactive Plotly preview and review warnings before export.",
    },
    {
        "id": "report",
        "label": "Explain / export",
        "description": "Export publication-ready graphics and pass structured context to the report agent.",
    },
]

PLOT_UI_METADATA: dict[str, dict[str, str]] = {
    "scatter": {
        "category": "Relationship",
        "thumbnail": "scatter",
        "use_case": "Two numeric variables, PCA scores, sample maps.",
    },
    "boxplot": {
        "category": "Distribution",
        "thumbnail": "boxplot",
        "use_case": "Group comparison with medians, spread, and raw points.",
    },
    "violin": {
        "category": "Distribution",
        "thumbnail": "violin",
        "use_case": "Group distribution shape and hidden multimodality.",
    },
    "bar": {
        "category": "Distribution",
        "thumbnail": "bar",
        "use_case": "Aggregated group summaries with error bars.",
    },
    "line": {
        "category": "Relationship",
        "thumbnail": "line",
        "use_case": "Ordered series, time course, and trajectory trends.",
    },
    "histogram": {
        "category": "Distribution",
        "thumbnail": "histogram",
        "use_case": "Single-variable distribution and value range checks.",
    },
    "density_contour": {
        "category": "Relationship",
        "thumbnail": "density_contour",
        "use_case": "Crowded two-variable scatter with density structure.",
    },
    "scatter_3d": {
        "category": "Relationship",
        "thumbnail": "scatter_3d",
        "use_case": "Three-axis separation, PCA-like embedding, feature space.",
    },
    "surface_3d": {
        "category": "Matrix",
        "thumbnail": "surface_3d",
        "use_case": "Expression-like matrices as interactive surface ridges.",
    },
    "radar": {
        "category": "Relationship",
        "thumbnail": "radar",
        "use_case": "Multi-metric sample or group profiles on a radial axis.",
    },
    "parallel_coordinates": {
        "category": "Relationship",
        "thumbnail": "parallel_coordinates",
        "use_case": "High-dimensional numeric profiles across many axes.",
    },
    "waterfall": {
        "category": "Omics results",
        "thumbnail": "waterfall",
        "use_case": "Ranked effect sizes, log2FC lists, or signed sample scores.",
    },
    "ma_plot": {
        "category": "Omics results",
        "thumbnail": "ma_plot",
        "use_case": "Mean abundance versus log2FC for differential expression checks.",
    },
    "qq_plot": {
        "category": "Omics results",
        "thumbnail": "qq_plot",
        "use_case": "Observed versus expected p-values for differential result diagnostics.",
    },
    "forest_plot": {
        "category": "Statistics",
        "thumbnail": "forest_plot",
        "use_case": "Effect sizes with confidence intervals across genes, terms, or comparisons.",
    },
    "roc_curve": {
        "category": "Statistics",
        "thumbnail": "roc_curve",
        "use_case": "Binary classification or biomarker score performance with AUC.",
    },
    "pr_curve": {
        "category": "Statistics",
        "thumbnail": "pr_curve",
        "use_case": "Precision-recall performance for imbalanced biomarker or classifier scores.",
    },
    "kaplan_meier": {
        "category": "Statistics",
        "thumbnail": "kaplan_meier",
        "use_case": "Survival or time-to-event curves with censor markers and log-rank context.",
    },
    "bland_altman": {
        "category": "Statistics",
        "thumbnail": "bland_altman",
        "use_case": "Agreement between two measurement methods with bias and limits of agreement.",
    },
    "dose_response": {
        "category": "Statistics",
        "thumbnail": "dose_response",
        "use_case": "Concentration-response or inhibition curves with IC50/EC50 context.",
    },
    "paired_dot": {
        "category": "Distribution",
        "thumbnail": "paired_dot",
        "use_case": "Before/after or matched-sample comparisons with subject-level connecting lines.",
    },
    "heatmap": {
        "category": "Matrix",
        "thumbnail": "heatmap",
        "use_case": "Scaled matrices with clustering and annotation.",
    },
    "bubble": {
        "category": "Relationship",
        "thumbnail": "bubble",
        "use_case": "X/Y position plus size and color encodings.",
    },
    "volcano": {
        "category": "Omics results",
        "thumbnail": "volcano",
        "use_case": "Differential result significance versus effect size.",
    },
    "upset": {
        "category": "Sets",
        "thumbnail": "upset",
        "use_case": "Multi-set intersections beyond simple Venn diagrams.",
    },
    "venn": {
        "category": "Sets",
        "thumbnail": "venn",
        "use_case": "Two- to four-set overlap sketches.",
    },
    "correlation": {
        "category": "Matrix",
        "thumbnail": "correlation",
        "use_case": "Sample similarity blocks with optional clustering.",
    },
    "enrichment_dot": {
        "category": "Omics results",
        "thumbnail": "enrichment_dot",
        "use_case": "Pathway or term enrichment overview.",
    },
}


def _param(
    param_id: str,
    label: str,
    param_type: str,
    default: Any = None,
    *,
    options: list[str] | None = None,
    min_value: float | None = None,
    max_value: float | None = None,
    step: float | None = None,
    required: bool = False,
    help_text: str = "",
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "id": param_id,
        "label": label,
        "type": param_type,
        "default": default,
        "required": required,
    }
    if options is not None:
        payload["options"] = options
    if min_value is not None:
        payload["min"] = min_value
    if max_value is not None:
        payload["max"] = max_value
    if step is not None:
        payload["step"] = step
    if help_text:
        payload["help"] = help_text
    return payload


def _group(group_id: str, label: str, parameters: list[dict[str, Any]]) -> dict[str, Any]:
    return {"id": group_id, "label": label, "parameters": parameters}


COMMON_THEME_GROUPS = [
    _group(
        "theme",
        "Palette and theme",
        [
            _param(
                "palette",
                "Palette",
                "select",
                "group",
                options=["group", "viridis", "blue_red", "prism_muted", "okabe_ito", "custom"],
            ),
            _param("background", "Background", "select", "white", options=["white", "transparent"]),
            _param(
                "font_family",
                "Font family",
                "select",
                "inter",
                options=["inter", "arial", "helvetica", "times", "georgia", "noto_sans"],
            ),
            _param("font_size", "Font size", "number", 13, min_value=8, max_value=28, step=1),
            _param("show_grid", "Show grid", "boolean", True),
            _param("grid_color", "Grid color", "color", "#e7eef4"),
            _param("grid_width", "Grid width", "number", 1.0, min_value=0.2, max_value=4, step=0.1),
            _param("show_zero_line", "Zero line", "boolean", True),
            _param("zero_line_color", "Zero line color", "color", "#b8c7d4"),
            _param("zero_line_width", "Zero line width", "number", 1.0, min_value=0.2, max_value=6, step=0.1),
            _param("axis_line", "Axis line", "boolean", True),
            _param("axis_line_color", "Axis line color", "color", "#425466"),
            _param("axis_line_width", "Axis line width", "number", 1.0, min_value=0.5, max_value=6, step=0.1),
            _param("axis_mirror", "Axis mirror", "select", "none", options=["none", "line", "ticks"]),
            _param("legend_position", "Legend", "select", "right", options=["right", "top", "bottom", "none"]),
            _param("legend_title", "Legend title", "text", ""),
            _param("legend_font_size", "Legend font size", "number", 12, min_value=8, max_value=24, step=1),
            _param("legend_background", "Legend background", "color", "rgba(255,255,255,0)"),
            _param("legend_border_color", "Legend border color", "color", "rgba(0,0,0,0)"),
            _param("legend_border_width", "Legend border width", "number", 0, min_value=0, max_value=6, step=0.1),
        ],
    ),
    _group(
        "labels",
        "Labels and axes",
        [
            _param("title", "Figure title", "text", ""),
            _param("subtitle", "Subtitle", "text", ""),
            _param("x_title", "X title", "text", ""),
            _param("y_title", "Y title", "text", ""),
            _param("title_position", "Title position", "select", "left", options=["left", "center"]),
            _param("title_font_size", "Title size", "number", 16, min_value=10, max_value=40, step=1),
            _param("title_color", "Title color", "color", "#07131f"),
            _param("subtitle_font_size", "Subtitle size", "number", 12, min_value=8, max_value=28, step=1),
            _param("subtitle_color", "Subtitle color", "color", "#617383"),
            _param("axis_title_font_size", "Axis title size", "number", 13, min_value=8, max_value=32, step=1),
            _param("axis_title_color", "Axis title color", "color", "#07131f"),
            _param("tick_font_size", "Tick label size", "number", 12, min_value=6, max_value=28, step=1),
            _param("tick_color", "Tick label color", "color", "#324657"),
            _param("tick_direction", "Tick direction", "select", "outside", options=["outside", "inside", "none"]),
            _param("tick_length", "Tick length", "number", 5, min_value=0, max_value=20, step=1),
            _param("tick_width", "Tick width", "number", 1, min_value=0, max_value=6, step=0.1),
            _param("tick_line_color", "Tick line color", "color", "#425466"),
            _param("x_range_mode", "X range", "select", "auto", options=["auto", "custom"]),
            _param("x_min", "X min", "number_or_auto", "auto"),
            _param("x_max", "X max", "number_or_auto", "auto"),
            _param("y_range_mode", "Y range", "select", "auto", options=["auto", "custom"]),
            _param("y_min", "Y min", "number_or_auto", "auto"),
            _param("y_max", "Y max", "number_or_auto", "auto"),
            _param("x_tick_count", "X tick count", "number_or_auto", "auto", min_value=2, max_value=30, step=1),
            _param("y_tick_count", "Y tick count", "number_or_auto", "auto", min_value=2, max_value=30, step=1),
            _param("x_tick_format", "X tick format", "text", ""),
            _param("y_tick_format", "Y tick format", "text", ""),
            _param("x_tick_prefix", "X tick prefix", "text", ""),
            _param("x_tick_suffix", "X tick suffix", "text", ""),
            _param("y_tick_prefix", "Y tick prefix", "text", ""),
            _param("y_tick_suffix", "Y tick suffix", "text", ""),
            _param("x_tick_angle", "X tick angle", "number", 0, min_value=-90, max_value=90, step=5),
            _param("y_tick_angle", "Y tick angle", "number", 0, min_value=-90, max_value=90, step=5),
        ],
    ),
    _group(
        "guides",
        "Guide lines",
        [
            _param("show_v_reference", "Vertical guide", "boolean", False),
            _param("v_reference_value", "Vertical value", "number_or_auto", "auto"),
            _param("v_reference_label", "Vertical label", "text", ""),
            _param("v_reference_color", "Vertical color", "color", "#475569"),
            _param("v_reference_width", "Vertical width", "number", 1.4, min_value=0.2, max_value=8, step=0.1),
            _param(
                "v_reference_dash",
                "Vertical dash",
                "select",
                "dash",
                options=["solid", "dash", "dot", "dashdot"],
            ),
            _param("show_h_reference", "Horizontal guide", "boolean", False),
            _param("h_reference_value", "Horizontal value", "number_or_auto", "auto"),
            _param("h_reference_label", "Horizontal label", "text", ""),
            _param("h_reference_color", "Horizontal color", "color", "#475569"),
            _param("h_reference_width", "Horizontal width", "number", 1.4, min_value=0.2, max_value=8, step=0.1),
            _param(
                "h_reference_dash",
                "Horizontal dash",
                "select",
                "dash",
                options=["solid", "dash", "dot", "dashdot"],
            ),
        ],
    ),
    _group(
        "interaction",
        "Interaction",
        [
            _param(
                "hover_mode",
                "Hover mode",
                "select",
                "closest",
                options=["closest", "x", "x unified", "y", "y unified", "none"],
                help_text="Controls whether hover follows points, axes, or a unified comparison label.",
            ),
            _param(
                "drag_mode",
                "Drag mode",
                "select",
                "zoom",
                options=["zoom", "pan", "select", "lasso", "orbit", "turntable", "none"],
                help_text="Default mouse drag behavior in the interactive Plotly canvas.",
            ),
            _param(
                "display_modebar",
                "Toolbar",
                "select",
                "hover",
                options=["hover", "always", "never"],
                help_text="Controls when Plotly's interactive toolbar is visible.",
            ),
            _param("scroll_zoom", "Scroll zoom", "boolean", False),
            _param("selection_tools", "Selection tools", "boolean", False),
            _param("show_spikes", "Axis hover guide", "boolean", False),
            _param("spike_color", "Guide color", "color", "#64748b"),
            _param("spike_width", "Guide width", "number", 1.0, min_value=0.2, max_value=6, step=0.1),
            _param("spike_dash", "Guide dash", "select", "dot", options=["solid", "dash", "dot", "dashdot"]),
            _param("hover_label_background", "Hover background", "color", "#111827"),
            _param("hover_label_color", "Hover text color", "color", "#ffffff"),
            _param("hover_label_font_size", "Hover text size", "number", 12, min_value=8, max_value=24, step=1),
        ],
    ),
    _group(
        "export",
        "Export size and format",
        [
            _param("width", "Width", "number", 1200, min_value=320, max_value=4000, step=10),
            _param("height", "Height", "number", 760, min_value=240, max_value=3000, step=10),
            _param("margin_left", "Left margin", "number", 72, min_value=20, max_value=300, step=1),
            _param("margin_right", "Right margin", "number", 32, min_value=10, max_value=300, step=1),
            _param("margin_top", "Top margin", "number", 72, min_value=20, max_value=300, step=1),
            _param("margin_bottom", "Bottom margin", "number", 64, min_value=20, max_value=300, step=1),
            _param("export_filename", "File name", "text", "yzw_biocloud_plot"),
            _param("dpi", "DPI", "select", "300", options=["150", "300", "600", "1000"]),
            _param("format", "Format", "select", "svg", options=["svg", "png", "jpeg", "webp"]),
        ],
    ),
]


PLOT_PRESETS: list[dict[str, Any]] = [
    {
        "id": "scatter",
        "label": "Scatter",
        "engine": "plotly",
        "description": "Two-variable relationship plot with optional group color, size mapping, and trend line.",
        "default_params": {
            "point_size": 8,
            "point_alpha": 0.85,
            "marker_line_width": 0.5,
            "marker_line_color": "#ffffff",
            "trendline": "none",
            "confidence_ellipse": False,
            "x_log": False,
            "y_log": False,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("x", "X axis", "column", None, required=True),
                    _param("y", "Y axis", "column", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                    _param("size", "Size by", "column_or_none", None),
                    _param("label", "Point label", "column_or_none", None),
                ],
            ),
            _group(
                "statistics",
                "Statistics and fit",
                [
                    _param("trendline", "Trend line", "select", "none", options=["none", "linear", "loess"]),
                    _param("loess_fraction", "LOESS span", "number", 0.35, min_value=0.15, max_value=0.9, step=0.05),
                    _param("confidence_ellipse", "Confidence ellipse", "boolean", False),
                    _param("ellipse_level", "Ellipse level", "number", 0.95, min_value=0.5, max_value=0.99, step=0.01),
                    _param("marker_line_width", "Marker line width", "number", 0.5, min_value=0, max_value=5, step=0.1),
                    _param("marker_line_color", "Marker line color", "color", "#ffffff"),
                    _param("x_log", "Log X axis", "boolean", False),
                    _param("y_log", "Log Y axis", "boolean", False),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "boxplot",
        "label": "Boxplot",
        "engine": "plotly",
        "description": "Grouped distribution plot with optional points, mean marker, and pairwise tests.",
        "default_params": {
            "show_points": True,
            "point_jitter": 0.35,
            "point_size": 5,
            "point_alpha": 0.72,
            "show_mean": True,
            "notched": False,
            "pairwise_test": "none",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("y", "Value", "column", None, required=True),
                    _param("group", "Group", "column", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                    _param("facet", "Facet by", "column_or_none", None),
                ],
            ),
            _group(
                "distribution",
                "Distribution display",
                [
                    _param("show_points", "Show individual points", "boolean", True),
                    _param("point_jitter", "Point jitter", "number", 0.35, min_value=0, max_value=1, step=0.05),
                    _param("point_size", "Point size", "number", 5, min_value=1, max_value=24, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.72, min_value=0.05, max_value=1, step=0.05),
                    _param("show_mean", "Show mean", "boolean", True),
                    _param("notched", "Notched boxes", "boolean", False),
                    _param("box_width", "Box width", "number", 0.62, min_value=0.2, max_value=1.0, step=0.02),
                ],
            ),
            _group(
                "statistics",
                "Statistics and error bars",
                [
                    _param(
                        "pairwise_test",
                        "Pairwise test",
                        "select",
                        "none",
                        options=["none", "t_test", "wilcoxon", "anova_then_tukey"],
                    ),
                    _param("multiple_testing", "Multiple testing", "select", "BH", options=["none", "BH", "bonferroni"]),
                    _param("show_p_values", "Show p-values", "boolean", False),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "violin",
        "label": "Violin",
        "engine": "plotly",
        "description": "Distribution shape plot for group comparisons, optionally overlaid with box and points.",
        "default_params": {
            "show_box": True,
            "show_mean": True,
            "show_points": "outliers",
            "span_mode": "soft",
            "side": "both",
            "point_size": 5,
            "point_alpha": 0.62,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("y", "Value", "column", None, required=True),
                    _param("group", "Group", "column", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                ],
            ),
            _group(
                "distribution",
                "Distribution display",
                [
                    _param("show_box", "Show box", "boolean", True),
                    _param("show_mean", "Show mean line", "boolean", True),
                    _param("show_points", "Points", "select", "outliers", options=["none", "outliers", "all"]),
                    _param("bandwidth", "Bandwidth", "number_or_auto", "auto", min_value=0.01, max_value=2.0, step=0.01),
                    _param("side", "Side", "select", "both", options=["both", "positive", "negative"]),
                    _param("point_size", "Point size", "number", 5, min_value=1, max_value=24, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.62, min_value=0.05, max_value=1, step=0.05),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "bar",
        "label": "Bar",
        "engine": "plotly",
        "description": "Summary bar chart with configurable aggregation and error bars.",
        "default_params": {
            "aggregation": "mean",
            "error_bar": "sem",
            "show_points": True,
            "orientation": "vertical",
            "sort": "input",
            "show_values": False,
            "value_precision": 2,
            "bar_width": 0.72,
            "pairwise_test": "none",
            "show_p_values": False,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("category", "Category", "column", None, required=True),
                    _param("value", "Value", "column", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                ],
            ),
            _group(
                "statistics",
                "Statistics and error bars",
                [
                    _param("aggregation", "Aggregation", "select", "mean", options=["mean", "median", "sum", "count"]),
                    _param("error_bar", "Error bar", "select", "sem", options=["none", "sd", "sem", "ci95"]),
                    _param("show_points", "Overlay raw points", "boolean", True),
                    _param("point_alpha", "Point opacity", "number", 0.68, min_value=0.05, max_value=1, step=0.05),
                    _param("error_cap_width", "Error cap width", "number", 8, min_value=0, max_value=24, step=1),
                    _param("show_values", "Show value labels", "boolean", False),
                    _param("value_precision", "Value precision", "number", 2, min_value=0, max_value=6, step=1),
                    _param("bar_width", "Bar width", "number", 0.72, min_value=0.1, max_value=1.0, step=0.02),
                    _param(
                        "pairwise_test",
                        "Pairwise test",
                        "select",
                        "none",
                        options=["none", "t_test", "wilcoxon", "anova_then_tukey"],
                    ),
                    _param("multiple_testing", "Multiple testing", "select", "BH", options=["none", "BH", "bonferroni"]),
                    _param("show_p_values", "Show p-values", "boolean", False),
                    _param("sort", "Sort bars", "select", "input", options=["input", "ascending", "descending"]),
                    _param("orientation", "Orientation", "select", "vertical", options=["vertical", "horizontal"]),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "line",
        "label": "Line",
        "engine": "plotly",
        "description": "Time-course or ordered series plot with optional grouping and smoothing.",
        "default_params": {
            "line_shape": "linear",
            "line_width": 2.4,
            "line_dash": "solid",
            "show_points": True,
            "marker_size": 6,
            "marker_symbol": "circle",
            "smooth": False,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("x", "X axis", "column", None, required=True),
                    _param("y", "Y axis", "column", None, required=True),
                    _param("series", "Series", "column_or_none", None),
                ],
            ),
            _group(
                "series",
                "Series display",
                [
                    _param("line_shape", "Line shape", "select", "linear", options=["linear", "spline", "hv", "vh"]),
                    _param("line_width", "Line width", "number", 2.4, min_value=0.5, max_value=10, step=0.1),
                    _param("line_dash", "Line dash", "select", "solid", options=["solid", "dash", "dot", "dashdot"]),
                    _param("show_points", "Show points", "boolean", True),
                    _param("marker_size", "Marker size", "number", 6, min_value=0, max_value=30, step=1),
                    _param("marker_symbol", "Marker symbol", "select", "circle", options=["circle", "square", "diamond", "cross", "x"]),
                    _param("smooth", "Smooth line", "boolean", False),
                    _param("connect_gaps", "Connect missing values", "boolean", False),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "histogram",
        "label": "Histogram",
        "engine": "plotly",
        "description": "Single-variable distribution chart with bins, density scaling, grouping, and cumulative display.",
        "default_params": {
            "bins": 30,
            "histnorm": "count",
            "barmode": "overlay",
            "opacity": 0.68,
            "bar_line_width": 0.5,
            "bar_line_color": "#ffffff",
            "cumulative": False,
            "show_mean": True,
            "show_median": False,
            "show_rug": False,
            "reference_line_width": 1.7,
            "reference_line_color_mode": "group",
            "reference_line_color": "#324657",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("x", "Value", "column", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                ],
            ),
            _group(
                "distribution",
                "Distribution display",
                [
                    _param("bins", "Bins", "number", 30, min_value=5, max_value=200, step=1),
                    _param("histnorm", "Scale", "select", "count", options=["count", "probability", "density", "probability density"]),
                    _param("barmode", "Bar mode", "select", "overlay", options=["overlay", "group", "stack"]),
                    _param("opacity", "Opacity", "number", 0.68, min_value=0.1, max_value=1, step=0.02),
                    _param("bar_line_width", "Bar line width", "number", 0.5, min_value=0, max_value=4, step=0.1),
                    _param("bar_line_color", "Bar line color", "color", "#ffffff"),
                    _param("cumulative", "Cumulative", "boolean", False),
                    _param("show_mean", "Mean reference", "boolean", True),
                    _param("show_median", "Median reference", "boolean", False),
                    _param("show_rug", "Rug marks", "boolean", False),
                ],
            ),
            _group(
                "reference",
                "Reference line style",
                [
                    _param("reference_line_width", "Line width", "number", 1.7, min_value=0.5, max_value=6, step=0.1),
                    _param(
                        "reference_line_color_mode",
                        "Color mode",
                        "select",
                        "group",
                        options=["group", "custom"],
                    ),
                    _param("reference_line_color", "Custom line color", "color", "#324657"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "radar",
        "label": "Radar",
        "engine": "plotly",
        "description": "Radial multi-metric profile chart for comparing sample rows or aggregated groups.",
        "default_params": {
            "max_series": 6,
            "aggregation": "mean",
            "normalize": "minmax_by_axis",
            "fill": True,
            "line_width": 2.2,
            "marker_size": 5,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("value_columns", "Metric columns", "numeric_columns", None, required=True),
                    _param("group", "Group / series", "column_or_none", None),
                    _param("label", "Row label", "column_or_none", None),
                ],
            ),
            _group(
                "profile",
                "Profile display",
                [
                    _param("max_series", "Max series", "number", 6, min_value=1, max_value=24, step=1),
                    _param("aggregation", "Group aggregation", "select", "mean", options=["mean", "median", "first"]),
                    _param(
                        "normalize",
                        "Normalize",
                        "select",
                        "minmax_by_axis",
                        options=["none", "minmax_by_axis", "zscore_by_axis"],
                    ),
                    _param("fill", "Fill polygons", "boolean", True),
                    _param("line_width", "Line width", "number", 2.2, min_value=0.5, max_value=8, step=0.1),
                    _param("marker_size", "Marker size", "number", 5, min_value=0, max_value=20, step=1),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "parallel_coordinates",
        "label": "Parallel coordinates",
        "engine": "plotly",
        "description": "High-dimensional numeric table scan with optional color mapping and row subsampling.",
        "default_params": {
            "max_dimensions": 8,
            "max_rows": 800,
            "color_scale": "viridis",
            "show_colorbar": True,
            "line_opacity": 0.58,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("dimensions", "Dimensions", "numeric_columns", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                    _param("label", "Row label", "column_or_none", None),
                ],
            ),
            _group(
                "dimensions",
                "Dimension display",
                [
                    _param("max_dimensions", "Max dimensions", "number", 8, min_value=3, max_value=24, step=1),
                    _param("max_rows", "Max rows", "number", 800, min_value=20, max_value=5000, step=1),
                    _param(
                        "color_scale",
                        "Color scale",
                        "select",
                        "viridis",
                        options=["viridis", "magma", "plasma", "cividis", "blue_white_red", "green_white_purple"],
                    ),
                    _param("show_colorbar", "Show color bar", "boolean", True),
                    _param("line_opacity", "Line opacity", "number", 0.58, min_value=0.05, max_value=1, step=0.02),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "density_contour",
        "label": "2D density contour",
        "engine": "plotly",
        "description": "Two-variable density contour with optional raw point overlay for crowded scatter data.",
        "default_params": {
            "contours_coloring": "heatmap",
            "show_points": True,
            "point_size": 5,
            "point_alpha": 0.38,
            "contour_line_width": 1.2,
            "show_contour_labels": False,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("x", "X axis", "column", None, required=True),
                    _param("y", "Y axis", "column", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                    _param("label", "Point label", "column_or_none", None),
                ],
            ),
            _group(
                "density",
                "Density display",
                [
                    _param("contours_coloring", "Contour fill", "select", "heatmap", options=["heatmap", "lines", "fill"]),
                    _param("show_points", "Overlay points", "boolean", True),
                    _param("point_size", "Point size", "number", 5, min_value=1, max_value=24, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.38, min_value=0.05, max_value=1, step=0.02),
                    _param("contour_line_width", "Contour line width", "number", 1.2, min_value=0.2, max_value=6, step=0.1),
                    _param("show_contour_labels", "Show contour labels", "boolean", False),
                    _param("contour_start", "Contour start", "number_or_auto", "auto"),
                    _param("contour_end", "Contour end", "number_or_auto", "auto"),
                    _param("contour_size", "Contour step", "number_or_auto", "auto"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "scatter_3d",
        "label": "3D scatter",
        "engine": "plotly",
        "description": "Three-axis interactive scatter plot for PCA-like or multi-feature numeric tables.",
        "default_params": {
            "marker_size": 5,
            "point_alpha": 0.78,
            "camera": "isometric",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("x", "X axis", "column", None, required=True),
                    _param("y", "Y axis", "column", None, required=True),
                    _param("z", "Z axis", "column", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                    _param("label", "Point label", "column_or_none", None),
                ],
            ),
            _group(
                "three_d",
                "3D display",
                [
                    _param("marker_size", "Marker size", "number", 5, min_value=1, max_value=30, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.78, min_value=0.05, max_value=1, step=0.02),
                    _param("camera", "Camera", "select", "isometric", options=["isometric", "front", "top"]),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "surface_3d",
        "label": "3D surface heatmap",
        "engine": "plotly",
        "description": "Matrix surface view for expression-like tables, ranked by row variance and optionally scaled.",
        "default_params": {
            "scale": "row_zscore",
            "top_n": 40,
            "colorscale": "Viridis",
            "show_contours": True,
            "camera": "isometric",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("row_id", "Row ID", "column", None),
                    _param("value_columns", "Value columns", "numeric_columns", None, required=True),
                ],
            ),
            _group(
                "surface",
                "Surface display",
                [
                    _param("scale", "Scale", "select", "row_zscore", options=["none", "row_zscore", "log2"]),
                    _param("top_n", "Top rows", "number", 40, min_value=5, max_value=2000, step=1),
                    _param("colorscale", "Colorscale", "select", "Viridis", options=["Viridis", "Plasma", "Cividis", "RdBu"]),
                    _param("show_contours", "Show contours", "boolean", True),
                    _param("camera", "Camera", "select", "isometric", options=["isometric", "front", "top"]),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "heatmap",
        "label": "Heatmap",
        "engine": "plotly",
        "description": "Matrix heatmap with row and column scaling, clustering, annotations, and labels.",
        "default_params": {
            "scale": "row_zscore",
            "cluster_rows": True,
            "cluster_columns": True,
            "show_dendrogram": True,
            "show_values": False,
            "value_precision": 2,
            "cell_gap": 1,
            "top_n": 50,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("row_id", "Row ID", "column", None),
                    _param("value_columns", "Value columns", "numeric_columns", None, required=True),
                    _param("column_annotation", "Column annotation", "column_or_none", None),
                    _param("row_annotation", "Row annotation", "column_or_none", None),
                ],
            ),
            _group(
                "clustering",
                "Clustering",
                [
                    _param("scale", "Scale", "select", "row_zscore", options=["none", "row_zscore", "column_zscore", "log2"]),
                    _param("cluster_rows", "Cluster rows", "boolean", True),
                    _param("cluster_columns", "Cluster columns", "boolean", True),
                    _param("show_dendrogram", "Show dendrogram", "boolean", True),
                    _param("distance", "Distance", "select", "correlation", options=["correlation", "euclidean", "manhattan"]),
                    _param("linkage", "Linkage", "select", "average", options=["average", "complete", "single", "ward"]),
                    _param("top_n", "Top rows", "number", 50, min_value=5, max_value=5000, step=1),
                ],
            ),
            _group(
                "cells",
                "Cell labels",
                [
                    _param("show_values", "Show cell values", "boolean", False),
                    _param("value_precision", "Value precision", "number", 2, min_value=0, max_value=6, step=1),
                    _param("cell_gap", "Cell gap", "number", 1, min_value=0, max_value=8, step=1),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "bubble",
        "label": "Bubble",
        "engine": "plotly",
        "description": "Scatter-like chart for x/y position plus size and color encodings.",
        "default_params": {
            "size_scale": 18,
            "min_bubble_size": 4,
            "max_bubble_size": 48,
            "color_scale": "viridis",
            "point_alpha": 0.72,
            "marker_line_width": 0.7,
            "marker_line_color": "#ffffff",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("x", "X axis", "column", None, required=True),
                    _param("y", "Y axis", "column", None, required=True),
                    _param("size", "Bubble size", "column", None, required=True),
                    _param("color", "Color by", "column_or_none", None),
                    _param("label", "Label", "column_or_none", None),
                ],
            ),
            _group(
                "bubble",
                "Bubble style",
                [
                    _param("size_scale", "Size scale", "number", 18, min_value=1, max_value=100, step=1),
                    _param("min_bubble_size", "Min bubble size", "number", 4, min_value=1, max_value=40, step=1),
                    _param("max_bubble_size", "Max bubble size", "number", 48, min_value=8, max_value=120, step=1),
                    _param(
                        "color_scale",
                        "Continuous color scale",
                        "select",
                        "viridis",
                        options=["viridis", "magma", "plasma", "cividis", "blue_white_red", "green_white_purple"],
                    ),
                    _param("point_alpha", "Point opacity", "number", 0.72, min_value=0.05, max_value=1, step=0.02),
                    _param("marker_line_width", "Marker line width", "number", 0.7, min_value=0, max_value=5, step=0.1),
                    _param("marker_line_color", "Marker line color", "color", "#ffffff"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "volcano",
        "label": "Volcano",
        "engine": "plotly",
        "description": "Differential result plot using log2 fold-change and significance thresholds.",
        "default_params": {
            "log2fc_column": "log2fc",
            "p_value_column": "p_value",
            "log2fc_threshold": 1.0,
            "p_value_threshold": 0.05,
            "show_threshold_lines": True,
            "threshold_line_width": 1.0,
            "threshold_line_dash": "dash",
            "threshold_line_color": "#8799aa",
            "label_top_n": 20,
            "label_font_size": 12,
            "point_size": 7,
            "point_alpha": 0.78,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("gene", "Gene label", "column", "gene"),
                    _param("log2fc_column", "log2FC", "column", "log2fc", required=True),
                    _param("p_value_column", "P value", "column", "p_value", required=True),
                ],
            ),
            _group(
                "thresholds",
                "Thresholds and labels",
                [
                    _param("log2fc_threshold", "Abs log2FC threshold", "number", 1.0, min_value=0, max_value=10, step=0.1),
                    _param("p_value_threshold", "P value threshold", "number", 0.05, min_value=0, max_value=1, step=0.001),
                    _param("show_threshold_lines", "Show threshold lines", "boolean", True),
                    _param("label_top_n", "Top labels", "number", 20, min_value=0, max_value=200, step=1),
                    _param("label_mode", "Label mode", "select", "significant", options=["none", "significant", "top_p", "custom"]),
                    _param("label_font_size", "Label font size", "number", 12, min_value=6, max_value=24, step=1),
                    _param("point_size", "Point size", "number", 7, min_value=1, max_value=24, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.78, min_value=0.05, max_value=1, step=0.02),
                ],
            ),
            _group(
                "style",
                "Threshold line style",
                [
                    _param("threshold_line_width", "Line width", "number", 1.0, min_value=0.5, max_value=6, step=0.1),
                    _param(
                        "threshold_line_dash",
                        "Line dash",
                        "select",
                        "dash",
                        options=["solid", "dash", "dot", "dashdot"],
                    ),
                    _param("threshold_line_color", "Line color", "color", "#8799aa"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "waterfall",
        "label": "Waterfall",
        "engine": "plotly",
        "description": "Ranked signed bar chart for effect sizes, differential log2FC values, and sample scores.",
        "default_params": {
            "value_column": "log2fc",
            "label_column": "gene",
            "p_value_column": "p_value",
            "sort_by": "abs_value",
            "top_n": 80,
            "orientation": "vertical",
            "color_mode": "significance",
            "positive_color": "#c44f3a",
            "negative_color": "#315fd6",
            "neutral_color": "#9aaab7",
            "bar_opacity": 0.88,
            "show_zero_line": True,
            "show_value_labels": False,
            "value_precision": 2,
            "log2fc_threshold": 1.0,
            "p_value_threshold": 0.05,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("label_column", "Label", "column", "gene"),
                    _param("value_column", "Signed value", "column", "log2fc", required=True),
                    _param("p_value_column", "P value", "column_or_none", "p_value"),
                    _param("group", "Group / category", "column_or_none", None),
                ],
            ),
            _group(
                "ranking",
                "Ranking and filtering",
                [
                    _param("sort_by", "Sort by", "select", "abs_value", options=["abs_value", "value_desc", "value_asc", "p_value", "input"]),
                    _param("top_n", "Top bars", "number", 80, min_value=1, max_value=5000, step=1),
                    _param("orientation", "Orientation", "select", "vertical", options=["vertical", "horizontal"]),
                    _param("log2fc_threshold", "Abs value threshold", "number", 1.0, min_value=0, max_value=20, step=0.1),
                    _param("p_value_threshold", "P value threshold", "number", 0.05, min_value=0, max_value=1, step=0.001),
                ],
            ),
            _group(
                "style",
                "Bar style",
                [
                    _param("color_mode", "Color mode", "select", "significance", options=["significance", "positive_negative", "group", "single"]),
                    _param("positive_color", "Positive color", "color", "#c44f3a"),
                    _param("negative_color", "Negative color", "color", "#315fd6"),
                    _param("neutral_color", "Neutral color", "color", "#9aaab7"),
                    _param("bar_opacity", "Bar opacity", "number", 0.88, min_value=0.05, max_value=1, step=0.02),
                    _param("show_zero_line", "Show zero line", "boolean", True),
                    _param("show_value_labels", "Show value labels", "boolean", False),
                    _param("value_precision", "Value precision", "number", 2, min_value=0, max_value=6, step=1),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "ma_plot",
        "label": "MA Plot",
        "engine": "plotly",
        "description": "Mean abundance versus log2 fold-change plot for differential expression diagnostics.",
        "default_params": {
            "mean_column": "baseMean",
            "log2fc_column": "log2fc",
            "p_value_column": "p_value",
            "gene": "gene",
            "x_log": True,
            "log2fc_threshold": 1.0,
            "p_value_threshold": 0.05,
            "show_threshold_lines": True,
            "label_top_n": 12,
            "point_size": 7,
            "point_alpha": 0.76,
            "up_color": "#c44f3a",
            "down_color": "#315fd6",
            "neutral_color": "#9aaab7",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("gene", "Gene label", "column_or_none", "gene"),
                    _param("mean_column", "Mean abundance", "column", "baseMean", required=True),
                    _param("log2fc_column", "log2FC", "column", "log2fc", required=True),
                    _param("p_value_column", "P value", "column_or_none", "p_value"),
                ],
            ),
            _group(
                "thresholds",
                "Thresholds and labels",
                [
                    _param("x_log", "Log X axis", "boolean", True),
                    _param("log2fc_threshold", "Abs log2FC threshold", "number", 1.0, min_value=0, max_value=20, step=0.1),
                    _param("p_value_threshold", "P value threshold", "number", 0.05, min_value=0, max_value=1, step=0.001),
                    _param("show_threshold_lines", "Show threshold lines", "boolean", True),
                    _param("label_top_n", "Top labels", "number", 12, min_value=0, max_value=200, step=1),
                    _param("point_size", "Point size", "number", 7, min_value=1, max_value=24, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.76, min_value=0.05, max_value=1, step=0.02),
                ],
            ),
            _group(
                "style",
                "Point colors",
                [
                    _param("up_color", "Up color", "color", "#c44f3a"),
                    _param("down_color", "Down color", "color", "#315fd6"),
                    _param("neutral_color", "Neutral color", "color", "#9aaab7"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "qq_plot",
        "label": "QQ Plot",
        "engine": "plotly",
        "description": "Observed versus expected p-value diagnostic plot for differential tests.",
        "default_params": {
            "p_value_column": "p_value",
            "label_column": "gene",
            "group": None,
            "max_points": 5000,
            "confidence_band": True,
            "confidence_level": 0.95,
            "show_diagonal": True,
            "label_top_n": 10,
            "point_size": 6,
            "point_alpha": 0.72,
            "band_color": "rgba(49, 95, 214, 0.16)",
            "diagonal_color": "#52616b",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("p_value_column", "P value", "column", "p_value", required=True),
                    _param("label_column", "Feature label", "column_or_none", "gene"),
                    _param("group", "Group / comparison", "column_or_none", None),
                ],
            ),
            _group(
                "diagnostics",
                "Diagnostics",
                [
                    _param("max_points", "Max points", "number", 5000, min_value=100, max_value=200000, step=100),
                    _param("confidence_band", "Confidence band", "boolean", True),
                    _param("confidence_level", "Confidence level", "select", "0.95", options=["0.90", "0.95", "0.99"]),
                    _param("show_diagonal", "Show expected line", "boolean", True),
                    _param("label_top_n", "Top labels", "number", 10, min_value=0, max_value=200, step=1),
                    _param("point_size", "Point size", "number", 6, min_value=1, max_value=24, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.72, min_value=0.05, max_value=1, step=0.02),
                ],
            ),
            _group(
                "style",
                "Diagnostic style",
                [
                    _param("band_color", "Band color", "color", "rgba(49, 95, 214, 0.16)"),
                    _param("diagonal_color", "Expected line color", "color", "#52616b"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "forest_plot",
        "label": "Forest Plot",
        "engine": "plotly",
        "description": "Horizontal effect-size plot with confidence intervals and optional significance coloring.",
        "default_params": {
            "label_column": "term",
            "effect_column": "effect",
            "ci_low_column": "ci_low",
            "ci_high_column": "ci_high",
            "p_value_column": "p_value",
            "group": None,
            "sort_by": "p_value",
            "top_n": 30,
            "reference_value": 0,
            "show_reference_line": True,
            "color_mode": "significance",
            "positive_color": "#c44f3a",
            "negative_color": "#315fd6",
            "neutral_color": "#9aaab7",
            "point_size": 9,
            "line_width": 1.8,
            "cap_width": 5,
            "point_alpha": 0.9,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("label_column", "Label", "column", "term", required=True),
                    _param("effect_column", "Effect size", "column", "effect", required=True),
                    _param("ci_low_column", "CI lower", "column", "ci_low", required=True),
                    _param("ci_high_column", "CI upper", "column", "ci_high", required=True),
                    _param("p_value_column", "P value", "column_or_none", "p_value"),
                    _param("group", "Group / comparison", "column_or_none", None),
                ],
            ),
            _group(
                "statistics",
                "Statistics and ordering",
                [
                    _param("sort_by", "Sort by", "select", "p_value", options=["p_value", "abs_effect", "effect_desc", "effect_asc", "input"]),
                    _param("top_n", "Top rows", "number", 30, min_value=1, max_value=500, step=1),
                    _param("reference_value", "Reference value", "number", 0, min_value=-100000, max_value=100000, step=0.1),
                    _param("show_reference_line", "Show reference line", "boolean", True),
                ],
            ),
            _group(
                "style",
                "Point and interval style",
                [
                    _param("color_mode", "Color mode", "select", "significance", options=["significance", "positive_negative", "group", "single"]),
                    _param("positive_color", "Positive color", "color", "#c44f3a"),
                    _param("negative_color", "Negative color", "color", "#315fd6"),
                    _param("neutral_color", "Neutral color", "color", "#9aaab7"),
                    _param("point_size", "Point size", "number", 9, min_value=1, max_value=32, step=1),
                    _param("line_width", "Interval line width", "number", 1.8, min_value=0.2, max_value=8, step=0.1),
                    _param("cap_width", "Cap width", "number", 5, min_value=0, max_value=20, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.9, min_value=0.05, max_value=1, step=0.02),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "roc_curve",
        "label": "ROC Curve",
        "engine": "plotly",
        "description": "Receiver operating characteristic curve with AUC for binary labels and numeric scores.",
        "default_params": {
            "score_column": "score",
            "label_column": "label",
            "positive_label": "auto",
            "group": None,
            "direction": "higher_positive",
            "show_diagonal": True,
            "show_auc": True,
            "show_threshold_points": False,
            "threshold_count": 12,
            "line_width": 2.6,
            "point_size": 6,
            "point_alpha": 0.8,
            "diagonal_color": "#8799aa",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("score_column", "Score", "column", "score", required=True),
                    _param("label_column", "Binary label", "column", "label", required=True),
                    _param("positive_label", "Positive label", "text", "auto"),
                    _param("group", "Group / model", "column_or_none", None),
                ],
            ),
            _group(
                "diagnostics",
                "ROC display",
                [
                    _param("direction", "Score direction", "select", "higher_positive", options=["higher_positive", "lower_positive"]),
                    _param("show_diagonal", "Show no-skill line", "boolean", True),
                    _param("show_auc", "Show AUC", "boolean", True),
                    _param("show_threshold_points", "Show threshold points", "boolean", False),
                    _param("threshold_count", "Threshold points", "number", 12, min_value=2, max_value=100, step=1),
                ],
            ),
            _group(
                "style",
                "Curve style",
                [
                    _param("line_width", "Line width", "number", 2.6, min_value=0.5, max_value=8, step=0.1),
                    _param("point_size", "Point size", "number", 6, min_value=1, max_value=24, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.8, min_value=0.05, max_value=1, step=0.02),
                    _param("diagonal_color", "No-skill line color", "color", "#8799aa"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "pr_curve",
        "label": "Precision-Recall",
        "engine": "plotly",
        "description": "Precision-recall curve with average precision for imbalanced binary labels.",
        "default_params": {
            "score_column": "score",
            "label_column": "label",
            "positive_label": "auto",
            "group": None,
            "direction": "higher_positive",
            "show_baseline": True,
            "show_average_precision": True,
            "show_threshold_points": False,
            "threshold_count": 12,
            "line_width": 2.6,
            "point_size": 6,
            "point_alpha": 0.8,
            "baseline_color": "#8799aa",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("score_column", "Score", "column", "score", required=True),
                    _param("label_column", "Binary label", "column", "label", required=True),
                    _param("positive_label", "Positive label", "text", "auto"),
                    _param("group", "Group / model", "column_or_none", None),
                ],
            ),
            _group(
                "diagnostics",
                "PR display",
                [
                    _param("direction", "Score direction", "select", "higher_positive", options=["higher_positive", "lower_positive"]),
                    _param("show_baseline", "Show prevalence baseline", "boolean", True),
                    _param("show_average_precision", "Show average precision", "boolean", True),
                    _param("show_threshold_points", "Show threshold points", "boolean", False),
                    _param("threshold_count", "Threshold points", "number", 12, min_value=2, max_value=100, step=1),
                ],
            ),
            _group(
                "style",
                "Curve style",
                [
                    _param("line_width", "Line width", "number", 2.6, min_value=0.5, max_value=8, step=0.1),
                    _param("point_size", "Point size", "number", 6, min_value=1, max_value=24, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.8, min_value=0.05, max_value=1, step=0.02),
                    _param("baseline_color", "Baseline color", "color", "#8799aa"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "kaplan_meier",
        "label": "Kaplan-Meier",
        "engine": "plotly",
        "description": "Time-to-event survival curve with censor markers and optional two-group log-rank test.",
        "default_params": {
            "time_column": "time",
            "event_column": "event",
            "group": "group",
            "event_value": "1",
            "censor_value": "0",
            "show_censor_marks": True,
            "show_confidence_band": False,
            "show_logrank": True,
            "show_risk_table": True,
            "time_unit": "time",
            "line_width": 2.6,
            "censor_marker_size": 7,
            "curve_mode": "survival",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("time_column", "Time", "column", "time", required=True),
                    _param("event_column", "Event status", "column", "event", required=True),
                    _param("group", "Group", "column_or_none", "group"),
                    _param("event_value", "Event value", "text", "1"),
                    _param("censor_value", "Censor value", "text", "0"),
                ],
            ),
            _group(
                "survival",
                "Survival display",
                [
                    _param("curve_mode", "Curve mode", "select", "survival", options=["survival", "failure"]),
                    _param("show_censor_marks", "Show censor marks", "boolean", True),
                    _param("show_confidence_band", "Confidence band", "boolean", False),
                    _param("show_logrank", "Show log-rank summary", "boolean", True),
                    _param("show_risk_table", "Attach risk table metadata", "boolean", True),
                    _param("time_unit", "Time unit", "text", "time"),
                ],
            ),
            _group(
                "style",
                "Curve style",
                [
                    _param("line_width", "Line width", "number", 2.6, min_value=0.5, max_value=8, step=0.1),
                    _param("censor_marker_size", "Censor marker size", "number", 7, min_value=2, max_value=24, step=1),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "bland_altman",
        "label": "Bland-Altman",
        "engine": "plotly",
        "description": "Agreement plot showing mean measurement versus pairwise difference, bias, and limits of agreement.",
        "default_params": {
            "x_method": None,
            "y_method": None,
            "label": None,
            "color": None,
            "difference_mode": "y_minus_x",
            "show_bias_line": True,
            "show_limits": True,
            "limits_sd": 1.96,
            "show_zero_line": True,
            "point_size": 8,
            "point_alpha": 0.78,
            "marker_line_width": 0.6,
            "marker_line_color": "#ffffff",
            "line_width": 1.4,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("x_method", "Method A", "column", None, required=True),
                    _param("y_method", "Method B", "column", None, required=True),
                    _param("label", "Point label", "column_or_none", None),
                    _param("color", "Color by", "column_or_none", None),
                ],
            ),
            _group(
                "agreement",
                "Agreement statistics",
                [
                    _param("difference_mode", "Difference", "select", "y_minus_x", options=["y_minus_x", "x_minus_y", "percent_difference"]),
                    _param("show_bias_line", "Show bias line", "boolean", True),
                    _param("show_limits", "Show limits of agreement", "boolean", True),
                    _param("limits_sd", "Limits SD multiplier", "number", 1.96, min_value=0.5, max_value=4, step=0.01),
                    _param("show_zero_line", "Show zero line", "boolean", True),
                ],
            ),
            _group(
                "style",
                "Point and line style",
                [
                    _param("point_size", "Point size", "number", 8, min_value=1, max_value=32, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.78, min_value=0.05, max_value=1, step=0.02),
                    _param("marker_line_width", "Marker line width", "number", 0.6, min_value=0, max_value=5, step=0.1),
                    _param("marker_line_color", "Marker line color", "color", "#ffffff"),
                    _param("line_width", "Reference line width", "number", 1.4, min_value=0.4, max_value=8, step=0.1),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "dose_response",
        "label": "Dose-response",
        "engine": "plotly",
        "description": "Concentration-response plot with grouped traces, log dose axis, and IC50/EC50 estimate metadata.",
        "default_params": {
            "dose_column": "concentration",
            "response_column": "response",
            "group": None,
            "label": None,
            "response_mode": "inhibition",
            "log_x": True,
            "normalize_response": False,
            "show_curve": True,
            "show_points": True,
            "show_half_max": True,
            "line_shape": "spline",
            "line_width": 2.6,
            "point_size": 8,
            "point_alpha": 0.78,
            "marker_line_width": 0.6,
            "marker_line_color": "#ffffff",
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("dose_column", "Dose / concentration", "column", "concentration", required=True),
                    _param("response_column", "Response", "column", "response", required=True),
                    _param("group", "Curve group", "column_or_none", None),
                    _param("label", "Point label", "column_or_none", None),
                ],
            ),
            _group(
                "curve",
                "Curve and estimate",
                [
                    _param("response_mode", "Response mode", "select", "inhibition", options=["inhibition", "activation", "raw"]),
                    _param("log_x", "Log dose axis", "boolean", True),
                    _param("normalize_response", "Normalize response", "boolean", False),
                    _param("show_curve", "Show connected curve", "boolean", True),
                    _param("show_points", "Show points", "boolean", True),
                    _param("show_half_max", "Show half-max guide", "boolean", True),
                    _param("line_shape", "Line shape", "select", "spline", options=["linear", "spline", "hv"]),
                ],
            ),
            _group(
                "style",
                "Point and line style",
                [
                    _param("line_width", "Line width", "number", 2.6, min_value=0.5, max_value=8, step=0.1),
                    _param("point_size", "Point size", "number", 8, min_value=1, max_value=32, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.78, min_value=0.05, max_value=1, step=0.02),
                    _param("marker_line_width", "Marker line width", "number", 0.6, min_value=0, max_value=5, step=0.1),
                    _param("marker_line_color", "Marker line color", "color", "#ffffff"),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "paired_dot",
        "label": "Paired Dot",
        "engine": "plotly",
        "description": "Matched-sample dot plot with subject-level connecting lines and optional group summaries.",
        "default_params": {
            "value_column": None,
            "condition_column": None,
            "subject_column": None,
            "group": None,
            "connect_pairs": True,
            "show_summary": True,
            "summary_stat": "mean",
            "max_subjects": 120,
            "point_size": 8,
            "point_alpha": 0.82,
            "line_width": 1.2,
            "line_alpha": 0.35,
            "jitter": 0.05,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("value_column", "Value", "column", None, required=True),
                    _param("condition_column", "Condition", "column", None, required=True),
                    _param("subject_column", "Subject / pair ID", "column", None, required=True),
                    _param("group", "Group", "column_or_none", None),
                ],
            ),
            _group(
                "paired",
                "Paired display",
                [
                    _param("connect_pairs", "Connect paired samples", "boolean", True),
                    _param("show_summary", "Show summary line", "boolean", True),
                    _param("summary_stat", "Summary", "select", "mean", options=["mean", "median"]),
                    _param("max_subjects", "Max subjects", "number", 120, min_value=2, max_value=2000, step=1),
                ],
            ),
            _group(
                "style",
                "Point and line style",
                [
                    _param("point_size", "Point size", "number", 8, min_value=1, max_value=32, step=1),
                    _param("point_alpha", "Point opacity", "number", 0.82, min_value=0.05, max_value=1, step=0.02),
                    _param("line_width", "Pair line width", "number", 1.2, min_value=0.2, max_value=8, step=0.1),
                    _param("line_alpha", "Pair line opacity", "number", 0.35, min_value=0.05, max_value=1, step=0.02),
                    _param("jitter", "Point jitter", "number", 0.05, min_value=0, max_value=0.45, step=0.01),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "upset",
        "label": "UpSet",
        "engine": "plotly",
        "description": "Set intersection chart for multiple gene lists or feature groups.",
        "default_params": {"min_intersection_size": 1, "max_sets": 8, "sort_by": "intersection_size"},
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("item_id", "Item ID", "column", None, required=True),
                    _param("set_columns", "Set columns", "columns", None, required=True),
                ],
            ),
            _group(
                "sets",
                "Set display",
                [
                    _param("min_intersection_size", "Min intersection", "number", 1, min_value=1, max_value=1000, step=1),
                    _param("max_sets", "Max sets", "number", 8, min_value=2, max_value=20, step=1),
                    _param("max_intersections", "Max intersections", "number", 40, min_value=5, max_value=120, step=1),
                    _param("sort_by", "Sort by", "select", "intersection_size", options=["intersection_size", "degree", "set_name"]),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "venn",
        "label": "Venn",
        "engine": "plotly",
        "description": "Two- to four-set overlap diagram for small set comparisons.",
        "default_params": {"max_sets": 4, "show_counts": True, "show_percent": False},
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("item_id", "Item ID", "column", None, required=True),
                    _param("set_columns", "Set columns", "columns", None, required=True),
                ],
            ),
            _group(
                "sets",
                "Set display",
                [
                    _param("max_sets", "Max sets", "number", 4, min_value=2, max_value=4, step=1),
                    _param("show_counts", "Show counts", "boolean", True),
                    _param("show_percent", "Show percent", "boolean", False),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "correlation",
        "label": "Correlation",
        "engine": "plotly",
        "description": "Correlation matrix heatmap with optional hierarchical clustering and group side bars.",
        "default_params": {
            "method": "pearson",
            "cluster_rows": True,
            "cluster_columns": True,
            "color_scale": "blue_white_red",
            "show_values": False,
            "value_precision": 2,
            "cell_gap": 1,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("value_columns", "Value columns", "numeric_columns", None, required=True),
                    _param("sample_group", "Sample group", "column_or_none", None),
                ],
            ),
            _group(
                "statistics",
                "Correlation settings",
                [
                    _param("method", "Method", "select", "pearson", options=["pearson", "spearman"]),
                    _param("cluster_rows", "Cluster rows", "boolean", True),
                    _param("cluster_columns", "Cluster columns", "boolean", True),
                    _param("show_values", "Show r values", "boolean", False),
                    _param("value_precision", "R value precision", "number", 2, min_value=0, max_value=4, step=1),
                    _param("cell_gap", "Cell gap", "number", 1, min_value=0, max_value=8, step=1),
                    _param(
                        "color_scale",
                        "Color scale",
                        "select",
                        "blue_white_red",
                        options=["blue_white_red", "viridis", "magma", "green_white_purple"],
                    ),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
    {
        "id": "enrichment_dot",
        "label": "Enrichment dot plot",
        "engine": "plotly",
        "description": "Pathway or term enrichment dot plot using ratio, count, and adjusted significance.",
        "default_params": {
            "term_column": "term",
            "x_column": "gene_ratio",
            "size_column": "count",
            "color_column": "adjusted_p",
            "color_transform": "minus_log10",
            "top_n": 20,
            "min_dot_size": 8,
            "max_dot_size": 38,
            "color_scale": "viridis",
            "point_alpha": 0.86,
        },
        "parameter_groups": [
            _group(
                "mapping",
                "Data mapping",
                [
                    _param("term_column", "Term", "column", "term", required=True),
                    _param("x_column", "X axis", "column", "gene_ratio", required=True),
                    _param("size_column", "Point size", "column", "count"),
                    _param("color_column", "Color", "column", "adjusted_p"),
                    _param("color_transform", "Color transform", "select", "minus_log10", options=["raw", "minus_log10"]),
                ],
            ),
            _group(
                "terms",
                "Term display",
                [
                    _param("top_n", "Top terms", "number", 20, min_value=5, max_value=200, step=1),
                    _param("sort_by", "Sort by", "select", "adjusted_p", options=["adjusted_p", "count", "gene_ratio"]),
                    _param("wrap_term_label", "Wrap labels", "boolean", True),
                    _param("term_label_width", "Label width", "number", 26, min_value=8, max_value=80, step=1),
                    _param("min_dot_size", "Min dot size", "number", 8, min_value=2, max_value=40, step=1),
                    _param("max_dot_size", "Max dot size", "number", 38, min_value=8, max_value=100, step=1),
                    _param(
                        "color_scale",
                        "Color scale",
                        "select",
                        "viridis",
                        options=["viridis", "magma", "plasma", "cividis", "blue_white_red", "green_white_purple"],
                    ),
                    _param("point_alpha", "Point opacity", "number", 0.86, min_value=0.05, max_value=1, step=0.02),
                ],
            ),
            *COMMON_THEME_GROUPS,
        ],
    },
]


RECOMMENDATIONS_BY_OUTPUT = {
    "gene_expression": ["boxplot", "violin", "bar", "histogram"],
    "paired": ["paired_dot", "boxplot", "line"],
    "pca": ["scatter", "bubble", "scatter_3d", "density_contour"],
    "sample_correlation": ["correlation", "heatmap"],
    "correlation": ["correlation", "heatmap"],
    "expression_heatmap": ["heatmap", "correlation"],
    "heatmap": ["heatmap", "correlation"],
    "volcano": ["volcano", "waterfall", "ma_plot", "qq_plot", "scatter"],
    "diff": ["volcano", "waterfall", "ma_plot", "qq_plot", "forest_plot", "heatmap", "bar"],
    "wgcna": ["heatmap", "bubble", "correlation", "density_contour"],
    "enrichment": ["enrichment_dot", "bar", "bubble"],
    "classification": ["roc_curve", "pr_curve", "scatter", "boxplot"],
    "biomarker": ["roc_curve", "pr_curve", "boxplot", "violin"],
    "survival": ["kaplan_meier", "forest_plot", "boxplot"],
    "agreement": ["bland_altman", "scatter", "correlation"],
    "dose": ["dose_response", "scatter", "line"],
    "expression_matrix": ["boxplot", "heatmap", "correlation", "histogram", "radar", "parallel_coordinates", "surface_3d"],
}


def _enrich_plot_preset(preset: dict[str, Any]) -> dict[str, Any]:
    enriched = deepcopy(preset)
    metadata = PLOT_UI_METADATA.get(enriched["id"], {})
    enriched["category"] = metadata.get("category", "Other")
    enriched["thumbnail"] = metadata.get("thumbnail", enriched["id"])
    enriched["use_case"] = metadata.get("use_case", enriched.get("description", ""))
    for group in enriched.get("parameter_groups", []):
        group["advanced"] = group.get("id") in ADVANCED_PARAMETER_GROUP_IDS
    return enriched


def list_plot_presets() -> list[dict[str, Any]]:
    return [_enrich_plot_preset(preset) for preset in PLOT_PRESETS]


def get_plot_studio_manifest() -> dict[str, Any]:
    return {
        "version": PLOT_STUDIO_VERSION,
        "engines": ["plotly"],
        "parameter_groups": [
            "Data mapping",
            "Grouping and facets",
            "Palette and theme",
            "Statistics and error bars",
            "Labels and annotations",
            "Export size and format",
        ],
        "workflow_stages": PLOT_WORKFLOW_STAGES,
        "presets": list_plot_presets(),
    }


def recommend_plot_types(source_type: str, table_summary: dict[str, Any] | None = None) -> list[str]:
    normalized_type = source_type.lower()
    for key, plot_ids in RECOMMENDATIONS_BY_OUTPUT.items():
        if key in normalized_type:
            return plot_ids[:]

    if table_summary:
        numeric_count = len(table_summary.get("numeric_columns") or [])
        categorical_count = len(table_summary.get("categorical_columns") or [])
        if numeric_count >= 2 and categorical_count >= 1:
            return ["scatter", "boxplot", "radar", "heatmap"]
        if numeric_count >= 2:
            return ["scatter", "correlation", "parallel_coordinates", "heatmap"]
        if numeric_count == 1 and categorical_count >= 1:
            return ["boxplot", "bar", "violin"]
    return ["scatter", "boxplot", "bar"]


